name: Format check

on:
  push:
  pull_request:
    branches: [master]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check on src directory
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "14"
          check-path: "src"

