name: tii-mavlink-router

on:
  repository_dispatch:
    types: [fog-ros-baseimage-update]
  push:
    branches: master
    tags: 
      - 'v*'
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
  pull_request:
    branches: [ master ]

jobs:
  tii-mavlink-router:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout mavlink-router
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: docker/setup-buildx-action@v1

      - name: Set image tag format without suffix
        run: |
          echo "IMAGE_TAG_FORMAT=type=sha" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Set image tag format with suffix
        # it is possible that run_number should be used instead run_attempt
        # run_attempt is unique number on every run and run_attempt resets to 1 if re-build is not used
        run: |
          echo "IMAGE_TAG_FORMAT=type=sha,suffix=-${{ github.event.client_payload.run_attempt }}" >> $GITHUB_ENV
        if: github.event_name == 'repository_dispatch'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/tii-mavlink-router
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
            ${{ env.IMAGE_TAG_FORMAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tii-mavlink-router image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
